# Generated by Django 4.1 on 2022-08-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
    ]
